version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gsh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.BUILD_VERSION={{.Version}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: gsh
    homepage: https://github.com/atinylittleshell/gsh
    description: The Generative Shell
    license: GPL-3.0
    directory: Formula
    commit_author:
      name: atinylittleshell
      email: shell@atinylittleshell.me
    repository:
      owner: atinylittleshell
      name: gsh
      token: "{{ .Env.GITHUB_TOKEN }}"
      branch: goreleaser/{{ .Version }}
      pull_request:
        enabled: true
        draft: false
        base:
          branch: main

aurs:
  - name: gsh-bin
    homepage: https://github.com/atinylittleshell/gsh
    description: The Generative Shell
    license: GPL-3.0
    maintainers:
      - "atinylittleshell <shell@atinylittleshell.me>"
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/gsh-bin.git"
    commit_author:
      name: atinylittleshell
      email: shell@atinylittleshell.me
    package: |-
      # bin
      install -Dm755 "./gsh" "${pkgdir}/usr/bin/gsh"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/gsh/LICENSE"
